src/main/java/com/techeersalon/moitda/global/common/SuccessCode.java
src/main/java/com/techeersalon/moitda/global/common/SuccessResponse.java
src/main/java/com/techeersalon/moitda/global/error/ErrorCode.java
src/main/java/com/techeersalon/moitda/global/error/ErrorResponse.java
src/main/java/com/techeersalon/moitda/global/error/GlobalExceptionHandler.java
src/main/java/com/techeersalon/moitda/global/error/exception/BusinessException.java

ErrorCode, SuccessCode 추가
---
일단 임시로 만들어놔서 나중에 개별적으로 API추가하면서 코드 작성해 주세요~
---
close #5

[chore] ErrorCode, SuccessCode 추가

---

build.gradle
compose.yaml
src/main/java/com/techeersalon/moitda/MoitdaApplication.java
src/main/java/com/techeersalon/moitda/controller/MeettingsController.java
src/main/resources/application.properties
src/main/resources/application.yml

---
spring 세팅 및 swagger 적용
---
#9

chore : spring 세팅 변경 및 swagger 적용

---

src/main/java/com/techeersalon/moitda/domain/user/controller/UserController.java
src/main/java/com/techeersalon/moitda/domain/user/dto/mapper/UserMapper.java
src/main/java/com/techeersalon/moitda/domain/user/dto/request/UpdateUserReq.java
src/main/java/com/techeersalon/moitda/domain/user/dto/response/UserProfileRes.java
src/main/java/com/techeersalon/moitda/domain/user/entity/User.java
src/main/java/com/techeersalon/moitda/domain/user/repository/UserRepository.java
src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java
src/main/java/com/techeersalon/moitda/global/config/SecurityConfig.java
src/main/java/com/techeersalon/moitda/global/jwt/JwtAuthenticationFilter.java
src/main/resources/application.yml
src/main/resources/static/index.html

---
유저 api 완료했습니다.
application.yml 보면  
web:
resources:
static-locations: /static/
이라 되어 있었는데 이렇게 하면 index.html이 기본으로 잡히지 않아(localhost:8080 들어갈 시 index.html이 잡히지 않음) 그 부분 수정했습니다.
---
#13

[feat] 유저 api 완료

---

src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/CreateMeetingParticipantRequest.java
src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/CreateMeetingRequest.java
src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/CreateMeetingResponse.java
src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetMeetingDetailResponse.java
src/main/java/com/techeersalon/moitda/domain/meetings/entity/Category.java
src/main/java/com/techeersalon/moitda/domain/meetings/entity/Meeting.java
src/main/java/com/techeersalon/moitda/domain/meetings/entity/MeetingParticipant.java
src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingParticipantRepository.java
src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingRepository.java
src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java
src/main/java/com/techeersalon/moitda/global/common/BaseEntity.java
src/main/resources/application.yml

---
모임 신청, 승인 api
모임 테이블 변경
참가자 관련 파일 작성
유저의 모든 모임 전달하는 함수
---
#19

[feat] 모임 신청, 승인 api / 참가자 entity 등 개발 

---

src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/CreateMeetingRequest.java
src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetMeetingDetailResponse.java
src/main/java/com/techeersalon/moitda/domain/meetings/entity/MeetingParticipant.java
src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingParticipantRepository.java
src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java

---
모임 생성시 host도 참가자 -> isWaiting은 false 바로 변경
모임 조회 api response에 참가자 List 추가
---
#23

[feat] 모임 생성시 host도 참가자 생성 / 모임 조회 api에 참가자 List 전송

---

src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/CreateMeetingRequest.java
src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetMeetingDetailResponse.java
src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java
src/main/java/com/techeersalon/moitda/global/config/SecurityConfig.java
src/main/java/com/techeersalon/moitda/global/config/WebConfig.java

webConfig 추가 및 meeting api 중 모임 생성 기능 수정
---
---

[fix] webConfig 추가 및 meeting api 중 모임 생성 기능 수정

---

compose.yaml
src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetMeetingDetailResponse.java
src/main/java/com/techeersalon/moitda/domain/meetings/entity/Meeting.java
src/main/java/com/techeersalon/moitda/domain/meetings/entity/MeetingParticipant.java
src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingParticipantRepository.java
src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingRepository.java
src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
src/main/java/com/techeersalon/moitda/domain/user/dto/mapper/UserMapper.java
src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java

[fix] meeting api 수정

---

src/main/java/com/techeersalon/moitda/chat/domain/UserChatRoom.java

fix : 빠진 파일 추가

---

src/main/java/com/techeersalon/moitda/domain/user/controller/UserController.java
src/main/java/com/techeersalon/moitda/domain/user/entity/User.java
src/main/java/com/techeersalon/moitda/domain/user/exception/UserNotFoundException.java
src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java
src/main/java/com/techeersalon/moitda/global/common/SuccessCode.java
src/main/java/com/techeersalon/moitda/global/common/SuccessResponse.java
src/main/java/com/techeersalon/moitda/global/error/ErrorResponse.java
src/main/java/com/techeersalon/moitda/global/jwt/Service/JwtService.java

[Refactor] user 응답처리 수정

---

src/main/java/com/techeersalon/moitda/global/config/SecurityConfig.java

---
@Bean
public CorsConfigurationSource corsConfigurationSource() {
CorsConfiguration config = new CorsConfiguration();
config.setAllowCredentials(true);
config.setAllowedOrigins(List.of(
"http://localhost:3000",
"http://jxy.me",
"http://apic.app",
"file://",
"https://jiangxy.github.io"
));
config.setAllowedMethods(List.of("GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"));
config.setAllowedHeaders(List.of("*"));
config.setExposedHeaders(List.of("*"));
UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
source.registerCorsConfiguration("/**", config);
return source;
}
---

feat : cors 에러 해결

---

build.gradle
src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/ChangeMeetingInfoReq.java
src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/CreateMeetingReq.java
src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetLatestMeetingListRes.java
src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetMeetingDetailRes.java
src/main/java/com/techeersalon/moitda/domain/meetings/entity/Meeting.java
src/main/java/com/techeersalon/moitda/domain/meetings/entity/MeetingImage.java
src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingImageRepository.java
src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
src/main/java/com/techeersalon/moitda/domain/user/controller/UserController.java
src/main/java/com/techeersalon/moitda/domain/user/dto/mapper/UserMapper.java
src/main/java/com/techeersalon/moitda/domain/user/dto/request/UpdateUserReq.java
src/main/java/com/techeersalon/moitda/domain/user/dto/response/UserMeetingRecordRes.java
src/main/java/com/techeersalon/moitda/domain/user/entity/User.java
src/main/java/com/techeersalon/moitda/domain/user/exception/UserAlreadyRegisteredException.java
src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java
src/main/java/com/techeersalon/moitda/global/config/MultipartJackson2HttpMessageConverter.java
src/main/java/com/techeersalon/moitda/global/config/S3Config.java
src/main/java/com/techeersalon/moitda/global/error/ErrorCode.java
src/main/java/com/techeersalon/moitda/global/jwt/JwtAuthenticationFilter.java
src/main/java/com/techeersalon/moitda/global/oauth/OAuth2LoginSuccessHandler.java
src/main/java/com/techeersalon/moitda/global/s3/exception/S3Exception.java

[feat] s3이미지 폼데이터 형식

---

src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetLatestMeetingListRes.java
src/main/java/com/techeersalon/moitda/domain/meetings/entity/Meeting.java
src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingRepository.java
src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
src/main/java/com/techeersalon/moitda/domain/user/controller/UserController.java

---
put api, list 0번째 이미지만 나오게 하기, 유저 히스토리 수정
---
#61

[fix] put api, list 0번째 이미지만 나오게 하기, 유저 히스토리 수정

---

src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
src/main/java/com/techeersalon/moitda/domain/meetings/dto/request/CreateReviewReq.java
src/main/java/com/techeersalon/moitda/domain/meetings/exception/review/InvalidRatingScoreException.java
src/main/java/com/techeersalon/moitda/domain/meetings/exception/review/MeetingNotEndedException.java
src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
src/main/java/com/techeersalon/moitda/domain/user/controller/UserController.java
src/main/java/com/techeersalon/moitda/domain/user/entity/User.java
src/main/java/com/techeersalon/moitda/global/common/SuccessCode.java
src/main/java/com/techeersalon/moitda/global/error/ErrorCode.java
src/main/java/com/techeersalon/moitda/global/oauth/OAuth2LoginSuccessHandler.java

---
후기 기능 (post)
mannerStat 점수 업데이트에 대한 대략적인 로직.
각 개인의 평가에 따라 -4 ~ 4점 부여할 수 있도록 했습니다.
---
#65

[feat] 후기 기능 구현

---

src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
src/main/java/com/techeersalon/moitda/domain/meetings/dto/mapper/MeetingParticipantListMapper.java
src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingParticipantRepository.java
src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
src/main/java/com/techeersalon/moitda/domain/user/controller/UserController.java
src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java
src/main/java/com/techeersalon/moitda/global/oauth/OAuthAttributes.java

---
---
[refactor : default mannerStat 20 -> 40]
[feat : 현재 사용자 조회 기능 추가]
[feat : 모임 상세조회 부분에서 참여자 필드에 isWaiting 추가]
[feat : 모임 수정 이미지 수정 로직 제거]
#77

[feat] 사용자 정보 조회 구현

---

src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java

---
MeetingService findMeetingById메서드 수정
---

[fix]MeetingService findMeetingById메서드 수정

---

src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetMeetingDetailRes.java
src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java

---
meeting service 수정
---
현재 조회한 유저가 "participant_list", "waiting_list" 안에 있는 유저 정보에 들어있는지 유무에 따라 participant_valid: true, false 지정.
#83

[fix] meeting service 수정

---

src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingRepository.java
src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java

---
검색시 end_time이 null인 데이터만 조회
레파지토리 함수 이름변경
키워드 검색
---
1. 모임 종료
2. 조회시 결과 (1번 데이터는 안나오는 걸보 볼 수 있다.)
```
{
"code": "M004",
"httpStatus": "OK",
"message": "모임 페이징 조회 성공",
"data": {
"meeting_list": [
{
"meeting_id": 4,
"category_id": 0,
"username": "주원",
"title": "string",
"image_url": null,
"road_address_name": "string",
"participants_count": 1,
"max_participants_count": 5,
"latitude": 36.8941,
"longitude": 127.3254
},
{
"meeting_id": 3,
"category_id": 0,
"username": "주원",
"title": "string",
"image_url": null,
"road_address_name": "string",
"participants_count": 1,
"max_participants_count": 5,
"latitude": 36.8941,
"longitude": 127.354
},
{
"meeting_id": 2,
"category_id": 0,
"username": "주원",
"title": "string",
"image_url": "https://moitda-image-storage.s3.ap-northeast-2.amazonaws.com/user/ …
```

[feat] end_time이 null인 데이터만 조회 가능, keyword검색

---

src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingRepository.java
src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java

---
기본 거리 모임 리스 조회 1.5km로 제한
---
핵심 코드
```
@Query(value = "SELECT * FROM meeting WHERE end_time IS NULL ORDER BY ST_Distance_Sphere(location_point, :point) <= 1500",
countQuery = "SELECT count(*) FROM meeting WHERE end_time IS NULL",
nativeQuery = true)
Page<Meeting> findMeetingByDistance(@Param("point") Point point, Pageable pageable);
```
테스트 결과

[feat] 기본 거리 모임 리스 조회 1.5km로 제한

---

.gitignore
build.gradle
compose.yaml
compose_dev.yaml
src/main/java/com/techeersalon/moitda/domain/chat/controller/StompChatController.java
src/main/java/com/techeersalon/moitda/global/config/RedisConfig.java
src/main/java/com/techeersalon/moitda/global/config/handler/StompHandler.java

gitignore, docker-compose_dev 수정
나머지 기능 관련된건 주석 처리해놓음
---
---

fix/#92 gitignore, docker-compose_dev 수정

---

src/main/java/com/techeersalon/moitda/domain/user/dto/mapper/UserMapper.java
src/main/java/com/techeersalon/moitda/domain/user/dto/response/UserProfileRes.java
src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java

fix : 타 사용자 정보 조회인지 구분

---

src/main/java/com/techeersalon/moitda/domain/user/service/UserService.java

---
userService s3 관련 수정
---
#110

[fix] userService s3 관련 수정

---

src/main/java/com/techeersalon/moitda/domain/meetings/dto/response/GetLatestMeetingListRes.java
src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingRepository.java
src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
src/main/java/com/techeersalon/moitda/domain/user/controller/UserController.java

---
회원 생성, 참여 내역 조회 수정
---
endTime 추가
#114

[fix] 회원 생성, 참여 내역 조회 수정

---

compose.yaml
nginx/nginx.conf
src/main/java/com/techeersalon/moitda/global/config/SecurityConfig.java
src/main/java/com/techeersalon/moitda/global/oauth/OAuth2LoginSuccessHandler.java

---
nginx 수정, docker-compose 수정
---
docker-compose에 frontend 작성하면서 nginx도 수정.
이제 compose 받아서 http://localhost 주소로 들어가면 됨.
#121

[fix] nginx 수정, docker-compose 수정

---

src/main/java/com/techeersalon/moitda/domain/chat/controller/ChatController.java
src/main/java/com/techeersalon/moitda/domain/chat/entity/ChatRoom.java
src/main/java/com/techeersalon/moitda/domain/chat/exception/AlreadyParticipatingException.java
src/main/java/com/techeersalon/moitda/domain/chat/exception/RoomOwnerCannotLeaveException.java
src/main/java/com/techeersalon/moitda/domain/chat/service/ChatRoomService.java
src/main/java/com/techeersalon/moitda/domain/meetings/controller/MeetingsController.java
src/main/java/com/techeersalon/moitda/domain/meetings/entity/Meeting.java
src/main/java/com/techeersalon/moitda/domain/meetings/exception/meeting/MeetingOwnerLeavingException.java
src/main/java/com/techeersalon/moitda/domain/meetings/repository/MeetingRepository.java
src/main/java/com/techeersalon/moitda/domain/meetings/service/MeetingService.java
src/main/java/com/techeersalon/moitda/domain/user/controller/UserController.java
src/main/java/com/techeersalon/moitda/domain/user/entity/User.java
src/main/java/com/techeersalon/moitda/global/common/SuccessCode.java
src/main/java/com/techeersalon/moitda/global/error/ErrorCode.java
src/main/java/com/techeersalon/moitda/global/jwt/JwtAuthenticationFilter.java

---
meeting, chat api 추가 및 수정
---
방장이 미팅 삭제 api 호출 시 예외처리.
채팅방도 마찬가지
일반 유저가 채팅방 나갈 시 
미팅 삭제도 마찬가지
이외 수정한 부분 확인했음.
그냥 급한대로 짜느라 일관성이라던지 이상한게 있을 수 있음. 잘 보고 확인해주셈
#125

[feat] meeting, chat api 추가 및 수정
